### PR TITLE
3.11 fortigate ruleset update

### PR DESCRIPTION
**Pull request by mikykeane**
Rewrote the whole decoder for fortigate from v5, also able to decode v5.6. 
Added decoders to work with 6.0 and 6.2.

Added rules and edited some that did not work correctly. 
Added .ini to enable testing.

### CODE REVIEW

**Comment by gr3gbarron** [comment]
Thanks for the update. This worked over the default install for version 6.

**Comment by coopjab** [comment]
how can i update the decoders ?

**Comment by coopjab** [comment]
how can i see fortigate web traffic in wazuh?????

**Comment by joselopezrio** [comment]
Hello @mikykeane,

We created the following PR to include your changes -> #592.

We are going to close this one.

Thank you for your collaboration.

**Pull request closed without merging**
