### PR TITLE
Update 0220-msauth_rules.xml

### PR DESCRIPTION
**Pull request by ecsc-georgew**
This catches RID values like "516001" as well as the intended "516".

Very minor tweak needed!

### CODE REVIEW

**Comment by ecsc-georgew** [comment]
Hi Eva,

Thanks for picking this one up. Here's an example log that triggers it for me:
2019 Aug 01 10:32:02 WinEvtLog: Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group.    Subject:   Security ID:  S-1-5-21-123456789-123456789-123456789-67473   Account Name:  ad_admin_person   Account Domain:  SW   Logon ID:  0x9A66976A    Member:   Security ID:  S-1-5-21-123456789-123456789-123456789-67491   Account Name:  cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL    Group:   Security ID:  S-1-5-21-123456789-123456789-123456789-51611   Group Name:  Some-Domain-Group   Group Domain:  CONTOSO    Additional Information:   Privileges:  -


Here's some shell output from an example test:

[root@termite ~]# echo "2019 Aug 01 10:32:02 WinEvtLog: Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group.    Subject:   Security ID:  S-1-5-21-123456789-123456789-123456789-67473   Account Name:  ad_admin_person   Account Domain:  SW   Logon ID:  0x9A66976A    Member:   Security ID:  S-1-5-21-123456789-123456789-123456789-67491   Account Name:  cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL    Group:   Security ID:  S-1-5-21-123456789-123456789-123456789-51611   Group Name:  Some-Domain-Group   Group Domain:  CONTOSO    Additional Information:   Privileges:  -" | /var/ossec/bin/ossec-logtest
2019/08/05 11:09:40 ossec-testrule: INFO: Compiled Rule Library /lib/rules/ecscrules.so opened
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so dump_eventinfo
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_destroy_agent
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_is_dst_ip_blacklisted
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_is_dst_ip_blacklisted_local_fh
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_is_ip_blacklisted
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_is_src_ip_blacklisted_local_fh
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_learn_ip
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/ecscrules.so kp_learn_ip_t
2019/08/05 11:09:40 ossec-testrule: INFO: Compiled Rule Library /lib/rules/genericrules.so opened
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/genericrules.so check_id_size
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/genericrules.so comp_mswin_targetuser_calleruser_diff
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/genericrules.so comp_srcuser_dstuser
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/genericrules.so is_simple_http_request
2019/08/05 11:09:40 ossec-testrule: INFO: Registered function /lib/rules/genericrules.so is_valid_crawler
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding dump_eventinfo
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_destroy_agent
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_is_dst_ip_blacklisted
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_is_dst_ip_blacklisted_local_fh
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_is_ip_blacklisted
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_is_src_ip_blacklisted_local_fh
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_learn_ip
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding kp_learn_ip_t
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding check_id_size
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding comp_mswin_targetuser_calleruser_diff
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding comp_srcuser_dstuser
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding is_simple_http_request
2019/08/05 11:09:40 ossec-testrule: INFO: compiled_rules_list: Adding is_valid_crawler
2019/08/05 11:09:40 ossec-testrule: INFO: Registered a total of 13 compiled rules

2019/08/05 11:09:41 ossec-testrule: INFO: Started (pid: 10208).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: '2019 Aug 01 10:32:02 WinEvtLog: Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group.    Subject:   Security ID:  S-1-5-21-123456789-123456789-123456789-67473   Account Name:  ad_admin_person   Account Domain:  SW   Logon ID:  0x9A66976A    Member:   Security ID:  S-1-5-21-123456789-123456789-123456789-67491   Account Name:  cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL    Group:   Security ID:  S-1-5-21-123456789-123456789-123456789-51611   Group Name:  Some-Domain-Group   Group Domain:  CONTOSO    Additional Information:   Privileges:  -'
       timestamp: '2019 Aug 01 10:32:02'
       hostname: 'termite'
       program_name: 'WinEvtLog'
       pid: '0'
       pid_len: '0'
       log: 'Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group.    Subject:   Security ID:  S-1-5-21-123456789-123456789-123456789-67473   Account Name:  ad_admin_person   Account Domain:  SW   Logon ID:  0x9A66976A    Member:   Security ID:  S-1-5-21-123456789-123456789-123456789-67491   Account Name:  cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL    Group:   Security ID:  S-1-5-21-123456789-123456789-123456789-51611   Group Name:  Some-Domain-Group   Group Domain:  CONTOSO    Additional Information:   Privileges:  -'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4728'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'DC01.CONTOSO.LOCAL'
       subject.security_id: 'S-1-5-21-123456789-123456789-123456789-67473'
       subject.account_name: 'ad_admin_person'
       subject.account_domain: 'SW'
       subject.logon_id: '0x9A66976A'
       security_id: 'S-1-5-21-123456789-123456789-123456789-67491'
       account_name: 'cn=Larry'

**Phase 3: Completed filtering (rules).
       Rule id: '18227'
       Level: '12'
       Description: 'Windows: Domain Controllers Group Changed'
       Info - Text: 'http://support.microsoft.com/kb/243330'
**Alert to be generated.

**Comment by Lopuiz** [comment]
Hi!

I regret to inform you that it does not match rule 18227:
```
root@lopezziur:/var/ossec# bin/ossec-logtest 
2019/08/05 12:41:12 ossec-testrule: INFO: Started (pid: 8811).
ossec-testrule: Type one log per line.

2019 Aug 01 10:32:02 WinEvtLog: Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group. Subject: Security ID: S-1-5-21-123456789-123456789-123456789-67473 Account Name: ad_admin_person Account Domain: SW Logon ID: 0x9A66976A Member: Security ID: S-1-5-21-123456789-123456789-123456789-67491 Account Name: cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL Group: Security ID: S-1-5-21-123456789-123456789-123456789-51611 Group Name: Some-Domain-Group Group Domain: CONTOSO Additional Information: Privileges: -


**Phase 1: Completed pre-decoding.
       full event: '2019 Aug 01 10:32:02 WinEvtLog: Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group. Subject: Security ID: S-1-5-21-123456789-123456789-123456789-67473 Account Name: ad_admin_person Account Domain: SW Logon ID: 0x9A66976A Member: Security ID: S-1-5-21-123456789-123456789-123456789-67491 Account Name: cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL Group: Security ID: S-1-5-21-123456789-123456789-123456789-51611 Group Name: Some-Domain-Group Group Domain: CONTOSO Additional Information: Privileges: -'
       timestamp: '2019 Aug 01 10:32:02'
       hostname: 'lopezziur'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4728): Microsoft-Windows-Security-Auditing: (no user): no domain: DC01.CONTOSO.LOCAL: A member was added to a security-enabled global group. Subject: Security ID: S-1-5-21-123456789-123456789-123456789-67473 Account Name: ad_admin_person Account Domain: SW Logon ID: 0x9A66976A Member: Security ID: S-1-5-21-123456789-123456789-123456789-67491 Account Name: cn=Larry David,OU=Administrative Accounts,OU=IT,OU=SPRINGFIELD,OU=User Accounts,DC=CONTOSO,DC=LOCAL Group: Security ID: S-1-5-21-123456789-123456789-123456789-51611 Group Name: Some-Domain-Group Group Domain: CONTOSO Additional Information: Privileges: -'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4728'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'DC01.CONTOSO.LOCAL'
       subject.security_id: 'S-1-5-21-123456789-123456789-123456789-67473'
       subject.account_name: 'ad_admin_person'
       subject.account_domain: 'SW'
       subject.logon_id: '0x9A66976A'
       security_id: 'S-1-5-21-123456789-123456789-123456789-67491'
       account_name: 'cn=Larry'

**Phase 3: Completed filtering (rules).
       Rule id: '18203'
       Level: '5'
       Description: 'Windows: Security Enabled Global Group Member Added'
       Info - Link: 'https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid=632'
**Alert to be generated.
```

Do you have custom rules and/or decoders? Also, I would like to know the Wazuh version installed.

Best regards,
Eva

**Comment by ecsc-georgew** [comment]
Hi Eva,

There are some custom rules and decoders involved. I have tried this on a few test installs with different versions, and it does seem to be inconsistent. So really I need to do a clean install with default ruleset get you a straight answer!

Apologies for the holdup, it did seem like a very simple problem at first but I should know by now there are NO simple problems :)

**Comment by Lopuiz** [comment]
Don't worry about it.
We are pleased with your interest in the Wazuh Ruleset project.

Regards,
Eva

**Comment by ecsc-georgew** [comment]
Hi Eva,

Embarrassing but I have the answer. The issue was already patched here:

https://github.com/wazuh/wazuh-ruleset/commit/961869cdfc21765d02e2b4e258b79925e45b20e5

BUT the box in question I was seeing a problem with had  an older ruleset on it due to a connectivity issue when pulling down the newer ones, so whilst it was getting updated rules from our own repo, it didn't have your central wazuh  "master" ruleset.

Never mind! Closing the pull request, thanks for your time and sorry to mess you around!

**Pull request closed without merging**
