### PR TITLE
Fixed Cisco-ios acl decoder and prematch

### LINKED ISSUE #205: Cisco ios decoders doesn't match certain log formats
Hello team,
there is an issue with the Cisco decoders not matching properly when the timestamp format isn't pre-decoded.
```
<decoder name="cisco-ios-acl">
  <parent>cisco-ios</parent>
  <type>firewall</type>
  <prematch>^%SEC-6-IPACCESSLOGP: </prematch>
  <regex offset="after_prematch">^list \S+ (\w+) (\w+) </regex>
  <regex>(\S+)\((\d+)\) -> (\S+)\((\d+)\),</regex>
  <order>action, protocol, srcip, srcport, dstip, dstport</order>
</decoder>
```
With the prematch forced to be at the start of the log, it doesn't work when the log include milliseconds or sequence number.

Also, I've found this access log including the Cisco interface and mac, not matching the regex.

`` 39222: *Oct  6 03:32:02.070 mng: %SEC-6-IPACCESSLOGP: list 167 denied udp xx.xx.xx.xx(137) (GigabitEthernet0/1.6 ab9c.2a62.aa8d) -> xxx.xxx.xxx.xxx(137), 1 packet  ``

Best regards,
Miguel

### PR DESCRIPTION
**Pull request by migruiz4**
Fixes #205 

Tested with this samples:
Logs with correct timestamp keeps working
``Oct  6 03:32:02 mng: %SEC-6-IPACCESSLOGP: list 1111 denied udp xx.xxx.xx.xx(137) -> xxx.xxx.xxx.xx(137), 1 packet ``

Logs with other not predecoded formats and log including interface being now decoded properly
``3924923: *Oct  6 03:32:04 mng: %SEC-6-IPACCESSLOGP: list 1111 denied tcp 10.0.3.100(50150) (Serial4/3 ) -> 192.168.216.1(443), 1 packet ``

``Oct  6 03:32:02 gmt: %SEC-6-IPACCESSLOGP: list bes_in denied udp xx.xxx.xx.xx(137) (GigabitEthernet0/1.6 ca5c.1da2.ba43) -> xx.xx.xx.xx(137), 1 packet ``

Regards,
Miguel

### CODE REVIEW

**Comment by migruiz4** [comment]
Added a second commit that solves issue #207

**Comment by migruiz4** [comment]
Added another commit to include the logs samples in the tests.
Regards,
Miguel R.

**Comment by okynos** [comment]
Hi @migruiz4 

This PR is failing with next error:

```
- [ File = ./tests/cisco_ios.ini ] ---------
......
------------------------------------------------------------
Failed: Exit code = 3
        Alert     = 0
        Rule      = 4100
        Decoder   = cisco-ios
        Section   = cisco ios: acl 
        line name = log 4 pass
 
2018/12/24 17:33:47 ossec-testrule: INFO: Started (pid: 2230).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: 'Oct 6 03:32:02 gmt: %SEC-6-IPACCESSLOGP: list bes_in denied udp xx.xxx.xx.xx(137) (GigabitEthernet0/1.6 ca5c.1da2.ba43) -> xx.xx.xx.xx(137), 1 packet'
       timestamp: '(null)'
       hostname: 'd86491263962'
       program_name: '(null)'
       log: 'Oct 6 03:32:02 gmt: %SEC-6-IPACCESSLOGP: list bes_in denied udp xx.xxx.xx.xx(137) (GigabitEthernet0/1.6 ca5c.1da2.ba43) -> xx.xx.xx.xx(137), 1 packet'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '1002'
       Level: '2'
       Description: 'Unknown problem somewhere in the system.'
lf->decoder_info->name: '(null)'
ut_decoder_name       : 'cisco-ios'
decoder matched : 'NULL'


- [ File = ./tests/proftpd.ini ] ---------
.......
- [ File = ./tests/oscap.ini ] ---------
................................
- [ File = ./tests/modsecurity.ini ] ---------
......
- [ File = ./tests/cimserver.ini ] ---------
..
- [ File = ./tests/vsftpd.ini ] ---------
....
- [ File = ./tests/apache.ini ] ---------
............
- [ File = ./tests/doas.ini ] ---------
....
- [ File = ./tests/dovecot.ini ] ---------
...............
- [ File = ./tests/pam.ini ] ---------
.....
- [ File = ./tests/opensmtpd.ini ] ---------
.......
- [ File = ./tests/nginx.ini ] ---------
............
- [ File = ./tests/sudo.ini ] ---------
........
- [ File = ./tests/exim.ini ] ---------
.....
- [ File = ./tests/samba.ini ] ---------
....
- [ File = ./tests/firewalld.ini ] ---------
..
- [ File = ./tests/netscreen.ini ] ---------
....
- [ File = ./tests/web_rules.ini ] ---------
.....
- [ File = ./tests/ossec.ini ] ---------
.....
- [ File = ./tests/syslog.ini ] ---------
.....
- [ File = ./tests/apparmor.ini ] ---------
.....
- [ File = ./tests/cpanel.ini ] ---------
.......
- [ File = ./tests/systemd.ini ] ---------
.
- [ File = ./tests/unbound.ini ] ---------

- [ File = ./tests/named.ini ] ---------
.....
- [ File = ./tests/postfix.ini ] ---------
..
- [ File = ./tests/web_appsec.ini ] ---------
...............................
- [ File = ./tests/rsh.ini ] ---------
..
- [ File = ./tests/su.ini ] ---------
.....
- [ File = ./tests/sysmon.ini ] ---------
...
- [ File = ./tests/mailscanner.ini ] ---------
.
- [ File = ./tests/sshd.ini ] ---------
...........................
```
 
Probably some test doesn't match the pattern, I really appreciate if you could fix, thanks.

Regards.

**Comment by 72nomada** [comment]
Hi @migruiz4, @okynos 

Can we consider closing this? 
Is there anyway to solve the issue detected by @okynos? if so, can we move this to wazuh/wazuh repo?

**Pull request closed without merging**
