### PR TITLE
Postfix decoder: Making ending doubled dot optional

### PR DESCRIPTION
**Pull request by iasdeoupxe**
Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4

### CODE REVIEW

**Comment by iasdeoupxe** [comment]
I'm not absolutely sure if this is the way to go / implement this because if the ending doubled dot is there the ``\S+`` operator might match this in the IP?

**Comment by Lopuiz** [comment]
Yes, you're right. I will study the way to match your log `Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4` with the decoder `postfix-warning`

**Comment by Lopuiz** [comment]
Hello @iasdeoupxe, 

How about this regex?
`<regex>^warning: (\S+):|warning: Illegal address syntax from unknown[(\S+)]|warning: hostname \S+ does not resolve to address (\d+.\d+.\d+.\d+)</regex>`

```
Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4:


**Phase 1: Completed pre-decoding.
       full event: 'Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4:'
       timestamp: 'Dec 14 22:23:34'
       hostname: 'myhost'
       program_name: 'postfix/smtpd'
       log: 'warning: hostname other.host does not resolve to address 1.2.3.4:'

**Phase 2: Completed decoding.
       decoder: 'postfix'
       srcip: '1.2.3.4'

**Phase 3: Completed filtering (rules).
       Rule id: '3398'
       Level: '6'
       Description: 'Postfix: Illegal address from unknown sender'
**Alert to be generated.
```

If you agree you can commit yourself

Regards, Eva

**Comment by iasdeoupxe** [comment]
Mhhh, but this is then only catching IPv4 addresses and would miss the IPv6 ones. Not sure but we probably need to have regex which matches both?

**Comment by Lopuiz** [comment]
@iasdeoupxe 
you could create multiple decoders

**Comment by iasdeoupxe** [comment]
Any suggestion for a IPv6 regex? I'm currently not even sure if such a complex regex like e.g. suggested in https://stackoverflow.com/a/17871737 is even possible with the Wazuh ruleset regex.

**Comment by Lopuiz** [comment]
No, this regex doesn't work

**Comment by iasdeoupxe** [comment]
So i'm currently stuck on proceed with this. Any suggestions on a regex which could match IPv4 AND IPv6 where the ending doubled dot could be removed?

**Comment by iasdeoupxe** [comment]
Could something like this working?

```
<regex>^warning: (\S+):|warning: Illegal address syntax from unknown[(\S+)]|warning: hostname \S+ does not resolve to address (\S+): |warning: hostname \S+ does not resolve to address (\S+)</regex>
```

Description:

If there is an ending dot in the regex the second one will match and isn't extracting the double dot into the IP, if there is no ending doubled dot the third regex will kick in.

**Comment by iasdeoupxe** [comment]
It looks indeed that this could work (ossec-logtest output with the suggested regex above).

```
Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4


**Phase 1: Completed pre-decoding.
       full event: 'Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4'
       timestamp: 'Dec 14 22:23:34'
       hostname: 'myhost'
       program_name: 'postfix/smtpd'
       log: 'warning: hostname other.host does not resolve to address 1.2.3.4'

**Phase 2: Completed decoding.
       decoder: 'postfix'
       srcip: '1.2.3.4'

**Phase 3: Completed filtering (rules).
       Rule id: '3398'
       Level: '6'
       Description: 'Postfix: Illegal address from unknown sender.'
**Alert to be generated.
```

and:

```
Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4: no address associated with name

**Phase 1: Completed pre-decoding.
       full event: 'Dec 14 22:23:34 myhost postfix/smtpd[27266]: warning: hostname other.host does not resolve to address 1.2.3.4: no address associated with name'
       timestamp: 'Dec 14 22:23:34'
       hostname: 'myhost'
       program_name: 'postfix/smtpd'
       log: 'warning: hostname other.host does not resolve to address 1.2.3.4: no address associated with name'

**Phase 2: Completed decoding.
       decoder: 'postfix'
       srcip: '1.2.3.4'

**Phase 3: Completed filtering (rules).
       Rule id: '3398'
       Level: '6'
       Description: 'Postfix: Illegal address from unknown sender.'
**Alert to be generated.
```

**Comment by iasdeoupxe** [comment]
Changed the PR in 4cb0cc7c3192b95c99676ea8795c0604b78ed42c with the suggested change from https://github.com/wazuh/wazuh-ruleset/pull/245#issuecomment-524205591

@Lopuiz This could be reviewed again.

**Comment by Lopuiz** [comment]
Hi!

I review it as soon as possible and it will merge in 3.11.
Thanks.

Regards,
Eva

**Comment by iasdeoupxe** [comment]
@Lopuiz Any updates on a review? Three months+ for such a minor change is a quite long time frame :cry:

**Pull request merged**
