### PR TITLE
Adding SCA policies for Windows Server 2019 RTM

### LINKED ISSUE #656: Development of SCA policies for Windows Server 2019
Hello team.
Working on the development of SCA policies for Windows Server 2019

It has been developed, strictly following the official CIS guidelines, using their latest official benchmark as reference: **CIS Microsoft Windows Server 2019 RTM (Release 1809) Benchmark v1.0.1 - 11-22-2019**

### PR DESCRIPTION
**Pull request by mikykeane**
Hello team, this PR aims to vastly improve our current SCA policy for Windows Server 2019 RTM. This PR closes #656 

It has been developed, strictly following the official CIS guidelines, using their latest official benchmark as reference: **CIS Microsoft Windows Server 2019 RTM (Release 1809) Benchmark v1.0.1 - 11-22-2019**

This PR adds all checks that are possible to automatize using the SCA module. It also improves some of the previously existing ones.

In addition, all checks have been studied and matched against suitable compliance guidelines, such as PCI, SOC and NIST among others. Enriching the information provided by each check, as it is now possible to know to which PCI requirements are each check related.

**Testing**

These checks have all been tested in different systems to be sure they were reliable in different environments.

- [x] Tested in the reliable vagrant box: rgl/windows-server-2019-standard-amd64 v 0.1.0
- [x] Tested in reliable vagrant box: rgl/windows-server-2019-standard-amd64
- [x] Tested in AWS Windows Server 2019 RTM machine.

### CODE REVIEW

**Comment by maxicloud** [comment]
Hello, do you already have a win20019 yml GPO available?

Thank's

**Comment by maxicloud** [comment]
@mikykeane 
Hello, do you already have a win20019 yml GPO available?

Thank's

**Comment by maxicloud** [comment]
cis win2019

**Comment by maxicloud** [comment]
Hi,

The win20019 yml file is not working

**Comment by mikykeane** [comment]
Hello @maxicloud 

What issues are you finding?
 
Is this the file that you are using? https://github.com/wazuh/wazuh-ruleset/blob/4.0-SCA/sca/windows/cis_win2019.yml

That latter one should work fine, but please let me know if you are finding any issue. 

Regards, 
Miguel Keane

**Comment by maxicloud** [comment]
Hi @mikykeane 

Displays a message on the SCA "No scans available". 

I'm using Windows Server 2019 Standard

The agent.conf file is correct.

<agent_config>
	<sca>
		<policies>
			<policy enabled="no">C:\Program Files (x86)\ossec-agent\ruleset\sca\sca_win_audit.yml</policy>
			<policy>C:\Program Files (x86)\ossec-agent\shared\cis_win2019.yml</policy>
		</policies>
	</sca>
</agent_config>

Thank's

**Pull request merged**
