### PR TITLE
GPG13 tags update

### PR DESCRIPTION
**Pull request by rossengeorgiev**
This is a continuation from #55

This PR updates the GPG13 tags on new rules and some of the existing ones.

### CODE REVIEW

**Comment by albertomn86** [comment]
Hi @rossengeorgiev,

Thanks for your contribution, we are going to review it and it will added to the Wazuh ruleset.

Best regards!

**Comment by rossengeorgiev** [comment]
Hi @albertomn86, thanks. This PR is now out of date as this repo is low on activity. I see that it marked to target wazuh 3.11. If that the case, I can set aside time to update it. Please let me know.

**Comment by albertomn86** [comment]
Hi @rossengeorgiev. Yes, this PR is planned to be included in Wazuh v3.11.0. 
We really appreciate your contribution.

Thanks!

**Comment by rossengeorgiev** [comment]
This PR is old and won't get updated

**Pull request closed without merging**
