### PR TITLE
Add GPG13 mappings to rules

### PR DESCRIPTION
**Pull request by rossengeorgiev**
#54 

I did 2 passes on the rules and some fresh eyes could help spot anything I've missed.

### CODE REVIEW

**Comment by jesuslinares** [comment]
Hi @rossengeorgiev,

it is awesome!, you did a great job. We are going to review it and it will added to the Wazuh ruleset.

Thanks so much!.

**Comment by rossengeorgiev** [comment]
Any movement on this? Should I bring the branch up date with master?

**Comment by BraulioV** [comment]
Hello @rossengeorgiev, 

sorry for the late response. We are reviewing your contribution and we will tell you about any news as soon as possible. 

Thank you for your patience.

Best regards,
Braulio.

**Comment by BraulioV** [comment]
Hello @rossengeorgiev,

I was reviewing your changes and I noticed that the rules version is _v2.1.0_ and you did the pull request to branch master. Currently, master's version is _v3.0.0-alpha2_, and this can cause problems in a fresh installation from sources. So, now there are two options:

1. Pull your branch master and get all the changes that we made on the repository, edit your changes and make a new pull request.
2. Change the branch where you want to merge your changes. To do that, you can click in the `Edit` button and change the branch from `base: master` to `base: 2.1`.

Thank you very much for your contribution.

Best regards,
Braulio

**Comment by rossengeorgiev** [comment]
Resync'd to `2.1` branch

**Comment by rossengeorgiev** [comment]
I haven't really looked how this matches with the `3.0` branch. I briefly saw some stuff being moved around.
Are there any plans on supporting gpg13 mapping on newly added rules or similar to PCI ?

**Comment by BraulioV** [comment]
Hello @rossengeorgiev,

sorry for the late response. We decided to introduce your changes with the next version of Wazuh (3.0), which it will be released soon.

By the way, awesome work! Thank you for your contribution!

Best regards,
Braulio.

**Comment by BraulioV** [comment]
> Are there any plans on supporting gpg13 mapping on newly added rules or similar to PCI ?

Every event matching some of the previous rules will contain the _gpg13_ group. You can create your own dashboards, similar to the PCI's dashboards that we already have, but right now, is not on our roadmap.

Any contribution about this will be really appreciated.

**Comment by rossengeorgiev** [comment]
Take a look at the commits in `3.0` branch it seems something has gone wrong with the merges.

https://github.com/wazuh/wazuh-ruleset/commits/3.0
https://github.com/wazuh/wazuh-ruleset/network
image

Is 3.0 the next release? I can submit a PR targeting that.

**Pull request merged**
