### PR TITLE
Cisco rules and decoders improvements

### LINKED ISSUE #205: Cisco ios decoders doesn't match certain log formats
Hello team,
there is an issue with the Cisco decoders not matching properly when the timestamp format isn't pre-decoded.
```
<decoder name="cisco-ios-acl">
  <parent>cisco-ios</parent>
  <type>firewall</type>
  <prematch>^%SEC-6-IPACCESSLOGP: </prematch>
  <regex offset="after_prematch">^list \S+ (\w+) (\w+) </regex>
  <regex>(\S+)\((\d+)\) -> (\S+)\((\d+)\),</regex>
  <order>action, protocol, srcip, srcport, dstip, dstport</order>
</decoder>
```
With the prematch forced to be at the start of the log, it doesn't work when the log include milliseconds or sequence number.

Also, I've found this access log including the Cisco interface and mac, not matching the regex.

`` 39222: *Oct  6 03:32:02.070 mng: %SEC-6-IPACCESSLOGP: list 167 denied udp xx.xx.xx.xx(137) (GigabitEthernet0/1.6 ab9c.2a62.aa8d) -> xxx.xxx.xxx.xxx(137), 1 packet  ``

Best regards,
Miguel

### LINKED ISSUE #207: Cisco ios doesn't match logs with  seq. number and no timezone
Hi team,
this logs from Cisco Switch, aren't decoded by the cisco-ios decoders

4425: Aug 23 00:17:55.356: %SSH-5-SSH2_SESSION: SSH2 Session request from x.x.x.x (tty = 0) using crypto cipher 'aes-111-sdf0', hmac 'hmac-sha1' Succeeded
4423: Aug 23 00:16:18.200: %SSH-5-SSH2_USERAUTH: User 'user' authentication for SSH2 Session from x.x.x.x (tty = 0) using crypto cipher 'aes111-sdf0', hmac 'hmac-sha1' Succeeded

Regards,
Miguel R.

### LINKED ISSUE #208: Cisco Accesslog and firewall rules doesn't match
Hi team,
while testing some rules, I noticed the decoder cisco-ios-acl can't trigger the firewall drop alerts.

This is a sample of cisco-acl log:
```
3924923: *Oct  6 03:32:04.114 gmt: %SEC-6-IPACCESSLOGP: list bcv_out denied tcp 10.0.3.100(50150) -> 192.168.216.1(443), 1 packet 
```

Actually is matching rule 4100
https://github.com/wazuh/wazuh-ruleset/blob/09b105a9db2436634b2723383202804b5ae732bd/rules/0060-firewall_rules.xml#L9-L13

And I think this should trigger the drop alert, because Cisco devices don't have the ACCEPT, REJECT, DROP actions.
Instead, they have "deny" and "permit"
So the equivalent to DROP would be "deny", and it doesn't match the rule. 

https://github.com/wazuh/wazuh-ruleset/blob/09b105a9db2436634b2723383202804b5ae732bd/rules/0060-firewall_rules.xml#L15-L24

Best regards,
Miguel

### LINKED ISSUE #210: Cisco IOS rules level
Hi team,
I've seen the level for the Cisco rules doesn't fit properly the level of the log.

The Cisco logs include in their name the [severity level](https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054858) of the alerts, as you can see [here](https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054485)

The severity level goes from 0 (emergency) to 7 (debug).

https://github.com/wazuh/wazuh-ruleset/blob/398d02dd079157c8599d4892c6c81ec797647d76/rules/0075-cisco-ios_rules.xml#L15-L66

When looking at the rules, I found the current severity / alert level looks like this.

| Level keyword  | Severity | Alert Level |
|---------------------|------------|--------------|
| emergencies     | 0            | 9            |
| alerts                 | 1            | 5              |
| critical                | 2            | 5              |
| errors                 | 3            | 4             |
| warnings            | 4            | 4              |
| ...                       |  5-7       |  0               |

I suggest modifying those levels to fit better the severity.
For example:

| Level keyword  | Severity | Alert Level |
|---------------------|------------|--------------|
| emergencies     | 0            | 10            |
| alerts                 | 1            | 7              |
| critical                | 2            | 5              |
| errors                 | 3            | 4             |
| warnings            | 4            | 3              |

Best regards,
Miguel R.

### LINKED ISSUE #269: PIX/ASA decoder disabled by Cisco IOS decoder
`0210-pix_decoders.xml` are not functioning. They match messages starting `%PIX-`, `%ASA-` or `%FWSM-` but they are neutered by `0065-cisco-ios_decoders.xml` which matches anything starting `%`

Options are:

1. Move 0210-pix_decoders.xml to 0062-cisco-pix_decoders.xml; or
2. Make the IOS matches more specific. They would need to match at least %IOS, %IOSXE, %SYS, %SEC, %IPS, there may be other patterns required.

So I think option 1 is the safer.

I will make a PR for this, as I need ASA decoding to work.

### LINKED ISSUE #379: Cisco logs match syslog rules
Hi team,

This cisco's log should match rule 4715.
>Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID` 
```
**Phase 1: Completed pre-decoding.
       full event: 'Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID'
       timestamp: '(null)'
       hostname: 'lopezziur-S551LN'
       program_name: '(null)'
       log: 'Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID'

**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '%DOT1X-5-FAIL'

**Phase 3: Completed filtering (rules).
       Rule id: '4715'
       Level: '6'
       Description: 'Cisco IOS notification message.'
**Alert to be generated.
```
This event is comunicated from agent by syslog. And its full log is `2019 May 06 09:28:12 vm-ubuntu16->10.0.0.16 May  6 07:28:11 vm-ubuntu16 fortinet Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID` (from archives.log).
This log match rule 2501 not 4715.

```
2019 May 06 09:28:12 vm-ubuntu16->10.0.0.16 May  6 07:28:11 vm-ubuntu16 fortinet Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID


**Phase 1: Completed pre-decoding.
       full event: '2019 May 06 09:28:12 vm-ubuntu16->10.0.0.16 May  6 07:28:11 vm-ubuntu16 fortinet Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID'
       timestamp: '2019 May 06 09:28:12'
       hostname: 'lopezziur-S551LN'
       program_name: '(null)'
       log: 'vm-ubuntu16->10.0.0.16 May  6 07:28:11 vm-ubuntu16 fortinet Apr 30 15:10:58: %DOT1X-5-FAIL: Authentication failed for client (Unknown MAC) on Interface Fa0/3 AuditSessionID'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2501'
       Level: '5'
       Description: 'syslog: User authentication failure.'
**Alert to be generated.
```

### PR DESCRIPTION
**Pull request by rossengeorgiev**
Hi Wazuh, in this PR I have addressed a number of issues with the Cisco rules and decoders:

1. Various decoder improvements. #207, #208, #379, #380, #205, #206, #209, #330
2. I've split the Cisco header into separate fields: `cisco.facility`, `cisco.severity`, `cisco.mnemonic`. This makes sense for the rules and when searching in Kibana
3. Reordered the `pix` decoder. #269, #270
4. Updated rule levels in the Cisco rules.  #207, #210 #337
5. Updated GPG13 mappings on the existing Cisco rules
6. Generic severity rules now include `cisco.mnemonic`

Auto closes all related issues and PRs:
Closes #207
Closes #208
Closes #379
Closes #380
Closes #205
Closes #206
Closes #209
Closes #330
Closes #269
Closes #270
Closes #207
Closes #210
Closes #337

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
Hi albertomn86, could you triage this one? Thanks

**Comment by chemamartinez** [comment]
Hi @rossengeorgiev,

First of all thanks for your contribution, it is an amazing job.

Unfortunately, we cannot merge your pull request yet. It is needed to review all the issues you say this PR is closing. Some of them have related pull requests opened, so we have to review both solutions (e.g. https://github.com/wazuh/wazuh-ruleset/pull/270).

Thanks for your patient.

Regards.

**Comment by rossengeorgiev** [comment]
Hi all, I've add some additional changes and rebased the PR against the `3.10` branch to avoid merge conflicts. There are still permutations of the logging settings that this decoder doesn't handle, but its unlikely they'll ever be used.

**Comment by rossengeorgiev** [comment]
Any update on this?

**Comment by 72nomada** [comment]
Hi @rossengeorgiev, sorry for delay, just a ping to verify whether this is still alive and waiting for us to do our work. 

Thanks

**Comment by rossengeorgiev** [comment]
Hi @72nomada, PR is from 1.5y ago. It was ready to go back then, but now I have no idea. Feel free to try and resolve it if you want. My rulesets have long diverged.

**Comment by 72nomada** [comment]
Thanks @rossengeorgiev, Thanks for your feedback. You are right, too old PR, sorry for that. Any chance we can have a feedback from/about your diverged rulesets? 

Thanks again and sorry for this as you did a great job here.

**Comment by rossengeorgiev** [comment]
A wide set of devices, and configurations, ware being fed through wazuh. The default decoders and rules often lacked. We maintain our own version of the default rules/decoders that includes many changes to achieve our use cases. Let me tell you, its not fun trying to rebase the changes on top of a new version of wazuh. This patch addresses the many variations of the cisco based syslogs, which is an issue in environments where the devices do not have identical logging configuration. Unfortunately, getting changes push upstream is difficult.

**Comment by juanrricci** [comment]
Hello team, we close this PR without applying the changes in this repository, but these were applied in the last Wazuh version repository with some modifications. They are detailed in the following issue: https://github.com/wazuh/wazuh/issues/7278.

**Pull request closed without merging**
