### PR TITLE
[rules] - modified rules and decoders to fetch more relevant data from full log

### PR DESCRIPTION
**Pull request by ankur-bb**
Please revie this PR, I have updated few rules and decoders to get more data out of full log field.

### CODE REVIEW

**Comment by Zenidd** [comment]
Hello @ankur-bb,

We are going to review this PR and if it is possible we will include it in Wazuh ruleset. 
Thank you very much for your contribution 


<br></br>
Best regards,

Juan Pablo Sáez

**Comment by ankur-bb** [comment]
Dear Eva,

Greetings!
Thank you for reviewing the PR.
I have checked the points highlighted by you, please find below comments:

1. <regex>Memory cgroup out of memory: Kill process (\d+) \((\w+)\) score (\d+) or sacrifice child</regex>
The regex works perfectly fine, the date input which you have mentioned in the examples are not correct.
Please check this PR which states that the date format should be "The TIMESTAMP field is the local time and is in the format of "Mmm dd hh:mm:ss" (without the quote marks)"
In your example there should be an extra space between Jun and 4, I have verified this in my wazuh alerts.json file which has extra space in the date to cater for the TIMESTAMP field format.
I have tried your example with the extra space and it worked fine:

```
Jun  4 11:06:01 lopezziur-S551LN kernel: [1075912.654097] Memory cgroup out of memory: Kill process 13089 (qemu-system-x86) score 302 or sacrifice child


**Phase 1: Completed pre-decoding.
       full event: 'Jun  4 11:06:01 lopezziur-S551LN kernel: [1075912.654097] Memory cgroup out of memory: Kill process 13089 (qemu-system-x86) score 302 or sacrifice child'
       timestamp: 'Jun  4 11:06:01'
       hostname: 'lopezziur-S551LN'
       program_name: 'kernel'
       log: '[1075912.654097] Memory cgroup out of memory: Kill process 13089 (qemu-system-x86) score 302 or sacrifice child'

**Phase 2: Completed decoding.
       decoder: 'kernel'

**Phase 3: Completed filtering (rules).
       Rule id: '5108'
       Level: '12'
       Description: 'System running out of memory. Availability of the system is in risk.'
**Alert to be generated. 
```

2. The windows file was not part of my change, I have to recheck how that went with this PR, apologies for the same.

Please let me know if I have to raise a different PR, and if so to which branch, as I can see you have changed the base to 3.10.

Regards,
Ankur

**Comment by ankur-bb** [comment]
Just to add, the windows file were not part of my commit:

[https://github.com/wazuh/wazuh-ruleset/pull/417/commits/01aaf4135b1a95b97297802b7e8ee4b21a405233](url)

Regards

**Comment by Lopuiz** [comment]
Hello Ankur,

First, sorry for the misunderstanding of the Windows file.

In your example, you don't get fields process_id, process_name, and score. That's because it doesn't match your decoder.
Try modifying the regex and you will get all the fields.

Adding `(\d+)` in regex the ossec-logtest output is:

```
Jun  4 11:06:01 lopezziur-S551LN kernel: [ 9724.809703]  Memory cgroup out of memory: Kill process 20316 (java) score 1016 or sacrifice child


**Phase 1: Completed pre-decoding.
       full event: 'Jun  4 11:06:01 lopezziur-S551LN kernel: [ 9724.809703]  Memory cgroup out of memory: Kill process 20316 (java) score 1016 or sacrifice child'
       timestamp: 'Jun  4 11:06:01'
       hostname: 'lopezziur-S551LN'
       program_name: 'kernel'
       log: '[ 9724.809703]  Memory cgroup out of memory: Kill process 20316 (java) score 1016 or sacrifice child'

**Phase 2: Completed decoding.
       decoder: 'kernel'
       process_id: '20316'
       process_name: 'java'
       score: '1016'

**Phase 3: Completed filtering (rules).
       Rule id: '5108'
       Level: '12'
       Description: 'System running out of memory. Availability of the system is in risk.'
**Alert to be generated.
```

Best regards, Eva

**Comment by ankur-bb** [comment]
Dear Eva,

Greetings,

Could you please tell me "Adding (\d+) in regex" which you have mentioned above, what's your regex looks like, because even I have (\d+) in my regex example and that worked for your examples as well.
Please can you paste your regex here so that I can match mine.

Regards,
Ankur

**Comment by Lopuiz** [comment]
Hi Ankur,

Of course, here's the decoders:
```xml
<!--
Jun  4 11:06:01 lopezziur-S551LN kernel: [1075912.654097] Memory cgroup out of memory: Kill process 13089 (qemu-system-x86) score 302 or sacrifice child
-->
<decoder name="kernel">
  <parent>kernel</parent>
  <!--<prematch>^/[\d+.\d+/]</prematch>-->
  <prematch>Memory cgroup out of memory</prematch>
  <regex>Memory cgroup out of memory: Kill process (\d+) \((\w+)\) score (\d+) or sacrifice child</regex>
  <order>process_id, process_name, score</order>
</decoder>
```

Kind regards, Eva

**Comment by ankur-bb** [comment]
Dear Eva,

Thank you for quick reply.
Please tell me how to go about this PR?
Should I raise a clean one for the latest branch 3.10?

Regards,
Ankur

**Comment by Lopuiz** [comment]
Hi,
you can try rebasing from 3.10.
You can follow this article: https://help.github.com/en/articles/about-git-rebase

Regards, Eva

**Comment by ankur-bb** [comment]
Dear Eva,

I have raised a new PR #423 after making required changes.
Please can you review the same.

Regards,
Ankur

**Comment by Lopuiz** [comment]
Okey

**Comment by Lopuiz** [comment]
Hello Ankur,

I close this PR because is duplicated.
For the next comments, we can use [this one](https://github.com/wazuh/wazuh-ruleset/pull/423)

Regards, Eva

**Pull request closed without merging**
