### PR TITLE
nextcloud rules, decoder, test.ini

### PR DESCRIPTION
**Pull request by banditopazzo**
added rules for nexcloud. I copied some rules from owncloud, while others are completely new.
the decoder is the same as owncloud, only changed the label.

### CODE REVIEW

**Comment by Lopuiz** [comment]
Hello,

Thank you so much for your contribution to the Ruleset project.
We will review and merge this PR as soon as possible.

For the moment, we need you do some modifications.

The files must have a blank line at the end:

imagen



The unit test `nextcloud.ini` doesn't work, it due to the logs which are in the file don't match Nextcloud rules and decoders. 

You can check it executing the script `tools/rules-testing/runtests.py`

To make the test works the rules and decoders must be add in `/var/ossec/ruleset/rules` and `/var/ossec/ruleset/decodes`.

Note some rules we have can match before with Nexcloud logs. You must have all our rules in the manager to execute the script if not the test isn't valid.

I attach the test result I have done:
[testNextcloud.txt](https://github.com/wazuh/wazuh-ruleset/files/3733002/testNextcloud.txt)

If you have any questions about the unit tests, let us know and we will help you. 

Best regards,
Eva

**Comment by banditopazzo** [comment]
Hi, thanks for the answer.

I have updated the files with the blank line at the end

About the test instead, my rules use first the json decoder, then my nextcloud decoder.

How to tell the test there are 2 decoders to match in sequence?
And how to run the test on my machine without having a full wazuh installation?

Regards

**Comment by Lopuiz** [comment]
Hello again!

You can use `Logtest` to testing and verification of rules and decoders. This tools is `/var/ossec/bin/ossec-logtest`. You can read more about it in our [documentation](https://documentation.wazuh.com/3.10/user-manual/reference/tools/ossec-logtest.html).

A `Logtest` output example is the following:
```
root@lopezziur:/var/ossec# bin/ossec-logtest 
2019/10/17 08:24:39 ossec-testrule: INFO: Started (pid: 8410).
ossec-testrule: Type one log per line.

{"reqId":"prLlx9+QIfl1jHtz9C5o","remoteAddr":"127.0.0.1","app":"core","message":"Login failed: 'admin' (Remote IP: '127.0.0.1)","level":2,"time":"2015-07-08T12:12:41+02:00","@source":"NextCloud"}


**Phase 1: Completed pre-decoding.
       full event: '{"reqId":"prLlx9+QIfl1jHtz9C5o","remoteAddr":"127.0.0.1","app":"core","message":"Login failed: 'admin' (Remote IP: '127.0.0.1)","level":2,"time":"2015-07-08T12:12:41+02:00","@source":"NextCloud"}'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '{"reqId":"prLlx9+QIfl1jHtz9C5o","remoteAddr":"127.0.0.1","app":"core","message":"Login failed: 'admin' (Remote IP: '127.0.0.1)","level":2,"time":"2015-07-08T12:12:41+02:00","@source":"NextCloud"}'

**Phase 2: Completed decoding.
       decoder: 'json'
       reqId: 'prLlx9+QIfl1jHtz9C5o'
       remoteAddr: '127.0.0.1'
       app: 'core'
       message: 'Login failed: 'admin' (Remote IP: '127.0.0.1)'
       level: '2'
       time: '2015-07-08T12:12:41+02:00'
       @source: 'NextCloud'

**Phase 3: Completed filtering (rules).
       Rule id: '88212'
       Level: '6'
       Description: 'NextCloud authentication failed.'
**Alert to be generated.
``` 

I input a Nextcloud log and it matches with Nexcloud rules you created. The decoder is JSON because it is the first to match (although it also matches the decoder you created).

But if I input any log come from `Nextcloud.ini`, it doesn't match any rule. It may due the Nextcloud decoder doesn't fire.


```
root@lopezziur:/var/ossec# bin/ossec-logtest 
2019/10/17 08:35:23 ossec-testrule: INFO: Started (pid: 9002).
ossec-testrule: Type one log per line.

{"reqId":"XaQ6fxNN-waxXQIsoJHOTQAAAAE","level":1,"time":"October 14, 2019 09:06:07","remoteAddr":"127.0.0.1","user":"admin","app":"admin_audit","method":"POST","url":"\/index.php\/login?user=admin","message":"Login successful: \"admin\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.120 Safari\/537.36","version":"16.0.5.1"}


**Phase 1: Completed pre-decoding.
       full event: '{"reqId":"XaQ6fxNN-waxXQIsoJHOTQAAAAE","level":1,"time":"October 14, 2019 09:06:07","remoteAddr":"127.0.0.1","user":"admin","app":"admin_audit","method":"POST","url":"\/index.php\/login?user=admin","message":"Login successful: \"admin\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.120 Safari\/537.36","version":"16.0.5.1"}'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '{"reqId":"XaQ6fxNN-waxXQIsoJHOTQAAAAE","level":1,"time":"October 14, 2019 09:06:07","remoteAddr":"127.0.0.1","user":"admin","app":"admin_audit","method":"POST","url":"\/index.php\/login?user=admin","message":"Login successful: \"admin\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.120 Safari\/537.36","version":"16.0.5.1"}'

**Phase 2: Completed decoding.
       decoder: 'json'
       reqId: 'XaQ6fxNN-waxXQIsoJHOTQAAAAE'
       level: '1'
       time: 'October 14, 2019 09:06:07'
       remoteAddr: '127.0.0.1'
       user: 'admin'
       app: 'admin_audit'
       method: 'POST'
       url: '/index.php/login?user=admin'
       message: 'Login successful: "admin"'
       userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36'
       version: '16.0.5.1'
```

It's important that unit test files are correct to test our Ruleset.

The test must be executed in a machine that has the Wazuh manager installed. The script execute the binary `ossec-logtest` with log declared in `log 1 pass`, and check it matches with the rule id (rule), rule level (alert) and decoder.

If all rules work correctly the `runtest.py` output must be as this:
[OutpuUnitTest.txt](https://github.com/wazuh/wazuh-ruleset/files/3737965/OutpuUnitTest.txt)

Best regards,
Eva

**Comment by banditopazzo** [comment]
OK thank you.

I updated the test file and the test output now is:
```bash
- [ File = ./tests/nextcloud.ini ] ---------
.......
```
You can check yourself

**Comment by banditopazzo** [comment]
Hi, I have updated the files with your requests

**Comment by Lopuiz** [comment]
Hello @banditopazzo 

Thanks for your quick response.

I'm sorry, I'm doing a lot of requests but I have doubts about the following decoder:

```xml
<decoder name="nextcloud-loglevel">
	<parent>nextcloud</parent>
	<prematch>","level":</prematch>
	<regex offset="after_prematch">^(\d),"</regex>
	<order>status</order>
</decoder>
```
I'm not sure that it matchs logs in Syslog format. It seems only match logs in JSON format.

Wazuh has a decoder implemented in C to decoding logs in JSON format. So it isn't necessary to create decoders in XML to decoding JSON.

To do a rule fires when a field has some value determine you can use option `field`. The rule could be as follow:

```xml
  <rule id="88206" level="4">
    <if_sid>88200,88201</if_sid>
    <field name="level">^3$</field>
    <description>NextCloud ERROR message.</description>
    <options>no_full_log</options>
  </rule>
```
And Logtest output is:
```
root@lopezziur:/var/ossec# bin/ossec-logtest 
2019/11/26 12:52:28 ossec-testrule: INFO: Started (pid: 12555).
ossec-testrule: Type one log per line.

{"reqId":"4ETnKW0UyDBNmL4z\/umV","remoteAddr":"127.0.0.1","app":"PHP","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/NextCloud\/lib\/private\/RedisFactory.php#60","level":3,"time":"2017-08-21T16:00:34+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/admin\/example\/","user":"admin","@source":"NextCloud"}



**Phase 1: Completed pre-decoding.
       full event: '{"reqId":"4ETnKW0UyDBNmL4z\/umV","remoteAddr":"127.0.0.1","app":"PHP","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/NextCloud\/lib\/private\/RedisFactory.php#60","level":3,"time":"2017-08-21T16:00:34+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/admin\/example\/","user":"admin","@source":"NextCloud"}'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '{"reqId":"4ETnKW0UyDBNmL4z\/umV","remoteAddr":"127.0.0.1","app":"PHP","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/NextCloud\/lib\/private\/RedisFactory.php#60","level":3,"time":"2017-08-21T16:00:34+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/admin\/example\/","user":"admin","@source":"NextCloud"}'

**Phase 2: Completed decoding.
       decoder: 'json'
       reqId: '4ETnKW0UyDBNmL4z/umV'
       remoteAddr: '127.0.0.1'
       app: 'PHP'
       message: 'Redis::connect(): connect() failed: No such file or directory at /var/www/NextCloud/lib/private/RedisFactory.php#60'
       level: '3'
       time: '2017-08-21T16:00:34+02:00'
       method: 'PROPFIND'
       url: '/remote.php/dav/addressbooks/users/admin/example/'
       user: 'admin'
       @source: 'NextCloud'

**Phase 3: Completed filtering (rules).
       Rule id: '88206'
       Level: '4'
       Description: 'NextCloud ERROR message.'
**Alert to be generated.
```

Could you modify rules 88205, 88206, 88207, 88208 and 88209 and delete `nextcloud-loglevel` decoder?

Also, I've noted rules 88208 and 88209 have level 0. I think the level of these rules should be 1 or 2.

Could you change it?

Best regards,
Eva

**Comment by banditopazzo** [comment]
Hi, I have updates the files with your fixes.

**Comment by Lopuiz** [comment]
Hello @banditopazzo,

I have one last question. Could you send me any log example which matches the following rule if it appears eight times?

```xml
  <rule id="88203" level="10" frequency="8" timeframe="120">
    <if_matched_sid>88202</if_matched_sid>
    <same_source_ip/>
    <description>NextCloud brute force (multiple failed logins).</description>
    <group>authentication_failures,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_11.4,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_SI.4,</group>
    <options>no_full_log</options>
  </rule>
```

I'm not sure it fires. But if option `<same_source_ip/>` is removed, it could match some logs.

I have noted Owncloud rules and decoders have some issues. I have reported it [here](https://github.com/wazuh/wazuh-ruleset/issues/533). I informed you because these errors may have confused you when creating Nextcloud rules and decoders. But I have already created [PR](https://github.com/wazuh/wazuh-ruleset/pull/534) to fix it.

Please, send us the log example or modify the rule.

Best regards,
Eva

**Comment by banditopazzo** [comment]
Hi, sorry for the delay, I was busy these days. 

However I have deleted the ```<same_source_ip/>``` entry in the rule.

This is an heritage of the Owncloud rule from which I "forked" for the creation of the Nextcloud rule.
In general there are some parts of the rules coming directly from the Owncloud ones I thinked were working correctly. If you encounter other problems let me know and I will try to understand the problem. But if you are sure enough about some issues, feel free to add edits yourself. I flagged the ```Allow edits from maintainers.``` checkbox.

Best regards

**Pull request merged**
